// Scent Atlas — structured fragrance database (MVP seed data)
// Follows PRD §9 data structure, extended with display fields.
const FRAGRANCES = [
  {
    id: "bleu-de-chanel",
    name: "Bleu de Chanel",
    brand: "Chanel",
    release_year: 2010,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Men",
    family: "Woody",
    accords: ["Woody", "Citrus", "Aromatic"],
    top_notes: ["Grapefruit", "Lemon", "Mint"],
    heart_notes: ["Ginger", "Nutmeg", "Jasmine"],
    base_notes: ["Sandalwood", "Cedar", "Incense"],
    mood: ["Elegant", "Confident", "Fresh"],
    season: ["Spring", "Autumn", "Winter"],
    time_of_day: ["Day", "Evening"],
    occasion: ["Office", "Dinner", "Daily"],
    style: ["Elegant", "Chic", "Minimalist"],
    description: "A refined woody-aromatic: bright citrus over dry cedar and sandalwood. Polished without being heavy.",
    featured: true, added_rank: 3, hue: 210
  },
  {
    id: "jadore-dior",
    name: "J'adore",
    brand: "Dior",
    release_year: 1999,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Women",
    family: "Floral",
    accords: ["Floral", "Fruity", "Fresh"],
    top_notes: ["Pear", "Melon", "Bergamot"],
    heart_notes: ["Jasmine", "Rose", "Ylang-Ylang"],
    base_notes: ["Musk", "Cedar"],
    mood: ["Elegant", "Romantic", "Radiant"],
    season: ["Spring", "Summer"],
    time_of_day: ["Day"],
    occasion: ["Wedding", "Daily", "Brunch"],
    style: ["Elegant", "Feminine", "Chic"],
    description: "A luminous bouquet of jasmine and rose with juicy pear. Classic, radiant, easy to love.",
    featured: true, added_rank: 10, hue: 45
  },
  {
    id: "black-opium-ysl",
    name: "Black Opium",
    brand: "Yves Saint Laurent",
    release_year: 2014,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Women",
    family: "Oriental/Amber",
    accords: ["Vanilla", "Coffee", "Sweet"],
    top_notes: ["Coffee", "Pear", "Pink Pepper"],
    heart_notes: ["Jasmine", "Orange Blossom"],
    base_notes: ["Vanilla", "Patchouli", "Musk"],
    mood: ["Bold", "Warm", "Seductive"],
    season: ["Autumn", "Winter"],
    time_of_day: ["Evening", "Night"],
    occasion: ["Date Night", "Party", "Evening Out"],
    style: ["Bold", "Glamorous", "Edgy"],
    description: "Addictive coffee-vanilla gourmand with jasmine sparkle. Warm, sweet, night-out energy.",
    featured: true, added_rank: 5, hue: 280
  },
  {
    id: "aventus-creed",
    name: "Aventus",
    brand: "Creed",
    release_year: 2010,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Men",
    family: "Chypre",
    accords: ["Fruity", "Woody", "Smoky"],
    top_notes: ["Pineapple", "Bergamot", "Blackcurrant"],
    heart_notes: ["Birch", "Patchouli", "Jasmine"],
    base_notes: ["Oakmoss", "Musk", "Vanilla"],
    mood: ["Confident", "Bold", "Powerful"],
    season: ["Spring", "Summer", "Autumn"],
    time_of_day: ["Day", "Evening"],
    occasion: ["Office", "Dinner", "Special Event"],
    style: ["Bold", "Luxurious", "Confident"],
    description: "Smoky pineapple and birch over oakmoss. The benchmark confident fruity-chypre.",
    featured: true, added_rank: 8, hue: 140
  },
  {
    id: "baccarat-rouge-540",
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    release_year: 2015,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Unisex",
    family: "Oriental/Amber",
    accords: ["Amber", "Woody", "Sweet"],
    top_notes: ["Saffron", "Jasmine"],
    heart_notes: ["Amberwood", "Ambergris"],
    base_notes: ["Fir Resin", "Cedar", "Musk"],
    mood: ["Luxurious", "Warm", "Magnetic"],
    season: ["Autumn", "Winter"],
    time_of_day: ["Evening", "Night"],
    occasion: ["Date Night", "Party", "Special Event"],
    style: ["Luxurious", "Elegant", "Bold"],
    description: "Airy amber woods with saffron glow. Sweet, radiant, instantly recognizable.",
    featured: true, added_rank: 2, hue: 0
  },
  {
    id: "light-blue-dg",
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    release_year: 2001,
    type: "Eau de Toilette",
    concentration: "EDT",
    gender: "Women",
    family: "Fresh",
    accords: ["Citrus", "Fresh", "Floral"],
    top_notes: ["Sicilian Lemon", "Apple", "Cedar"],
    heart_notes: ["Bamboo", "Jasmine", "White Rose"],
    base_notes: ["Cedar", "Musk", "Amber"],
    mood: ["Fresh & Clean", "Joyful", "Carefree"],
    season: ["Spring", "Summer"],
    time_of_day: ["Day", "Morning"],
    occasion: ["Daily", "Beach", "Brunch", "Office"],
    style: ["Casual", "Fresh", "Minimalist"],
    description: "Crisp Sicilian lemon and apple over clean musk. The classic fresh summer daytime scent.",
    featured: false, added_rank: 14, hue: 190
  },
  {
    id: "terre-dhermes",
    name: "Terre d'Hermès",
    brand: "Hermès",
    release_year: 2006,
    type: "Eau de Toilette",
    concentration: "EDT",
    gender: "Men",
    family: "Woody",
    accords: ["Earthy", "Woody", "Citrus"],
    top_notes: ["Orange", "Grapefruit"],
    heart_notes: ["Pepper", "Flint"],
    base_notes: ["Vetiver", "Cedar", "Patchouli"],
    mood: ["Grounded", "Elegant", "Earthy"],
    season: ["Spring", "Autumn"],
    time_of_day: ["Day"],
    occasion: ["Office", "Daily", "Dinner"],
    style: ["Elegant", "Understated", "Classic"],
    description: "Mineral citrus over vetiver and flint. Earthy, refined, quietly confident.",
    featured: false, added_rank: 12, hue: 30
  },
  {
    id: "sauvage-dior",
    name: "Sauvage",
    brand: "Dior",
    release_year: 2015,
    type: "Eau de Toilette",
    concentration: "EDT",
    gender: "Men",
    family: "Fresh",
    accords: ["Fresh", "Aromatic", "Woody"],
    top_notes: ["Bergamot", "Pepper"],
    heart_notes: ["Lavender", "Geranium", "Sichuan Pepper"],
    base_notes: ["Ambroxan", "Cedar", "Musk"],
    mood: ["Fresh & Clean", "Bold", "Confident"],
    season: ["Spring", "Summer"],
    time_of_day: ["Day", "Evening"],
    occasion: ["Daily", "Office", "Casual", "Evening Out"],
    style: ["Casual", "Bold", "Modern"],
    description: "Bergamot and pepper blasted with ambroxan. Fresh, loud, crowd-pleasing.",
    featured: false, added_rank: 9, hue: 200
  },
  {
    id: "coco-mademoiselle",
    name: "Coco Mademoiselle",
    brand: "Chanel",
    release_year: 2001,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Women",
    family: "Chypre",
    accords: ["Citrus", "Floral", "Patchouli"],
    top_notes: ["Orange", "Bergamot"],
    heart_notes: ["Rose", "Jasmine", "Lychee"],
    base_notes: ["Patchouli", "Vanilla", "Musk"],
    mood: ["Elegant", "Chic", "Confident"],
    season: ["Spring", "Autumn", "Winter"],
    time_of_day: ["Day", "Evening"],
    occasion: ["Office", "Dinner", "Date Night"],
    style: ["Chic", "Elegant", "Classic"],
    description: "Sparkling orange-rose over patchouli-vanilla. Polished, chic, endlessly wearable.",
    featured: true, added_rank: 11, hue: 340
  },
  {
    id: "oud-wood-tomford",
    name: "Oud Wood",
    brand: "Tom Ford",
    release_year: 2007,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Unisex",
    family: "Woody",
    accords: ["Woody", "Smoky", "Warm"],
    top_notes: ["Rosewood", "Cardamom"],
    heart_notes: ["Oud", "Sandalwood", "Vetiver"],
    base_notes: ["Tonka Bean", "Amber", "Musk"],
    mood: ["Warm", "Mysterious", "Elegant"],
    season: ["Autumn", "Winter"],
    time_of_day: ["Evening", "Night"],
    occasion: ["Dinner", "Date Night", "Special Event"],
    style: ["Elegant", "Mysterious", "Luxurious"],
    description: "Smooth, approachable oud wrapped in sandalwood and cardamom. Warm woods, no harsh edges.",
    featured: true, added_rank: 4, hue: 25
  },
  {
    id: "flowerbomb-vr",
    name: "Flowerbomb",
    brand: "Viktor & Rolf",
    release_year: 2005,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Women",
    family: "Floral",
    accords: ["Floral", "Sweet", "Powdery"],
    top_notes: ["Orchid", "Tea", "Bergamot"],
    heart_notes: ["Jasmine", "Rose", "Orchid"],
    base_notes: ["Patchouli", "Musk"],
    mood: ["Romantic", "Joyful", "Glamorous"],
    season: ["Spring", "Winter"],
    time_of_day: ["Day", "Evening"],
    occasion: ["Party", "Wedding", "Date Night"],
    style: ["Glamorous", "Romantic", "Feminine"],
    description: "Explosive orchid-jasmine bouquet on patchouli. Sweet, powdery, celebratory florals.",
    featured: false, added_rank: 13, hue: 300
  },
  {
    id: "acqua-di-gio",
    name: "Acqua di Giò",
    brand: "Giorgio Armani",
    release_year: 1996,
    type: "Eau de Toilette",
    concentration: "EDT",
    gender: "Men",
    family: "Fresh",
    accords: ["Aquatic", "Citrus", "Fresh"],
    top_notes: ["Lime", "Lemon", "Bergamot"],
    heart_notes: ["Sea Notes", "Jasmine", "Rosemary"],
    base_notes: ["White Musk", "Cedar", "Patchouli"],
    mood: ["Fresh & Clean", "Calm", "Carefree"],
    season: ["Summer", "Spring"],
    time_of_day: ["Day", "Morning"],
    occasion: ["Beach", "Daily", "Casual", "Office"],
    style: ["Casual", "Fresh", "Minimalist"],
    description: "Sea breeze citrus with jasmine and musk. The archetypal clean aquatic.",
    featured: false, added_rank: 15, hue: 180
  },
  {
    id: "santal-33-lelabo",
    name: "Santal 33",
    brand: "Le Labo",
    release_year: 2011,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Unisex",
    family: "Woody",
    accords: ["Woody", "Leathery", "Spicy"],
    top_notes: ["Cardamom", "Violet"],
    heart_notes: ["Sandalwood", "Papyrus", "Iris"],
    base_notes: ["Leather", "Cedar", "Amber"],
    mood: ["Cool", "Minimalist", "Edgy"],
    season: ["Autumn", "Winter", "Spring"],
    time_of_day: ["Day", "Evening"],
    occasion: ["Casual", "Daily", "Evening Out", "Creative Work"],
    style: ["Minimalist", "Edgy", "Modern"],
    description: "Creamy sandalwood with leather and cardamom. Cool, urban, cult-favorite woods.",
    featured: true, added_rank: 1, hue: 90
  },
  {
    id: "la-vie-est-belle",
    name: "La Vie Est Belle",
    brand: "Lancôme",
    release_year: 2012,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Women",
    family: "Gourmand",
    accords: ["Sweet", "Floral", "Powdery"],
    top_notes: ["Blackcurrant", "Pear"],
    heart_notes: ["Iris", "Jasmine", "Orange Blossom"],
    base_notes: ["Vanilla", "Praline", "Tonka Bean"],
    mood: ["Joyful", "Warm & Cozy", "Romantic"],
    season: ["Autumn", "Winter"],
    time_of_day: ["Day", "Evening"],
    occasion: ["Daily", "Dinner", "Holiday"],
    style: ["Feminine", "Cozy", "Classic"],
    description: "Iris-praline gourmand with vanilla warmth. Sweet, cozy, radiant happiness.",
    featured: false, added_rank: 16, hue: 320
  },
  {
    id: "phantom-fougere",
    name: "Phantom Fougère",
    brand: "Qubators Atelier",
    release_year: 2024,
    type: "Eau de Parfum",
    concentration: "EDP",
    gender: "Unisex",
    family: "Fougère",
    accords: ["Aromatic", "Herbal", "Woody"],
    top_notes: ["Lavender", "Bergamot", "Clary Sage"],
    heart_notes: ["Geranium", "Rosemary"],
    base_notes: ["Tonka Bean", "Oakmoss", "Musk"],
    mood: ["Fresh & Clean", "Confident", "Timeless"],
    season: ["Spring", "Summer", "Autumn"],
    time_of_day: ["Day", "Morning"],
    occasion: ["Office", "Daily", "Wedding"],
    style: ["Classic", "Minimalist", "Chic"],
    description: "Modern barbershop fougère: lavender and sage over tonka-oakmoss. Clean, timeless, emerging-house take.",
    featured: false, added_rank: 6, hue: 160
  },
  {
    id: "vanilla-noir-lumiere",
    name: "Vanilla Noir",
    brand: "Maison Lumière",
    release_year: 2022,
    type: "Extrait de Parfum",
    concentration: "Extrait",
    gender: "Unisex",
    family: "Gourmand",
    accords: ["Vanilla", "Amber", "Woody"],
    top_notes: ["Rum", "Bergamot"],
    heart_notes: ["Vanilla Bourbon", "Jasmine"],
    base_notes: ["Sandalwood", "Musk", "Amber", "Tonka Bean"],
    mood: ["Warm & Cozy", "Seductive", "Warm"],
    season: ["Autumn", "Winter"],
    time_of_day: ["Evening", "Night"],
    occasion: ["Date Night", "Dinner", "Holiday"],
    style: ["Cozy", "Luxurious", "Romantic"],
    description: "Dark rum-vanilla with sandalwood and musk. Warm, enveloping, perfect vanilla + sandalwood + musk combo.",
    featured: true, added_rank: 7, hue: 35
  },
  {
    id: "citrus-bloom-indie",
    name: "Citrus Bloom",
    brand: "Petite Fleur Studio",
    release_year: 2023,
    type: "Eau de Toilette",
    concentration: "EDT",
    gender: "Unisex",
    family: "Fresh",
    accords: ["Citrus", "Floral", "Green"],
    top_notes: ["Yuzu", "Bergamot", "Neroli"],
    heart_notes: ["Orange Blossom", "Green Tea"],
    base_notes: ["Musk", "Cedar"],
    mood: ["Fresh & Clean", "Joyful", "Radiant"],
    season: ["Spring", "Summer"],
    time_of_day: ["Morning", "Day"],
    occasion: ["Brunch", "Beach", "Daily", "Office"],
    style: ["Minimalist", "Fresh", "Casual"],
    description: "Sparkling yuzu-neroli with orange blossom tea. Bright indie fresh-floral for summer days.",
    featured: false, added_rank: 17, hue: 55
  },
  {
    id: "mystic-oud-niche",
    name: "Mystic Oud",
    brand: "Ambre Nuit Niche",
    release_year: 2021,
    type: "Extrait de Parfum",
    concentration: "Extrait",
    gender: "Unisex",
    family: "Oriental/Amber",
    accords: ["Smoky", "Woody", "Resinous"],
    top_notes: ["Saffron", "Bergamot"],
    heart_notes: ["Oud", "Rose", "Incense"],
    base_notes: ["Amber", "Leather", "Musk", "Patchouli"],
    mood: ["Mysterious", "Bold", "Magnetic"],
    season: ["Winter", "Autumn"],
    time_of_day: ["Night", "Evening"],
    occasion: ["Special Event", "Evening Out", "Date Night"],
    style: ["Bold", "Mysterious", "Luxurious"],
    description: "Smoky oud-rose with incense and amber. Deep, resinous, unapologetically dramatic niche amber.",
    featured: false, added_rank: 18, hue: 265
  }
];
